---
- name: Configure linux development environment
  hosts: localhost
  connection: local
  become: yes

  tasks:
      - name: Perform System Update
        pacman:
          update_cache: yes
          upgrade: yes

      - name: Install Required Packages
        pacman:
          name: "{{ item }}"
          state: present
        loop:
          - htop
          - fzf
          - ripgrep
          - fd
          - tmux
          - openssh
          - firefox
          - cmake
          - npm
          - unzip
          - zip
          - lsof
          - tree
          - curl
          - less
          - vim
          - nvim
          - wayland
          - wayland-protocols
          - wlroots0.19
          - wl-clipboard
          - wlr-randr
          - foot
          - base-devel
          - grim
          - slurp
          - swaybg
          - swayimg
          - tllist
          - fcft
          - pixman
          - ttf-jetbrains-mono-nerd
          - pipewire
          - pipewire-pulse
          - pipewire-alsa
          - wireplumber

      - name: Create Config Directory
        ansible.builtin.file:
          path: /home/{{ ansible_env.SUDO_USER }}/.config
          state: directory
          owner: "{{ ansible_env.SUDO_USER }}"
          group: "{{ ansible_env.SUDO_USER }}"
          mode: "0755"

      - name: Copy Files to Directories
        copy: 
          src: "{{ item.src }}"
          dest: "{{ item.dest }}"
          owner: "{{ ansible_env.SUDO_USER }}"
          group: "{{ ansible_env.SUDO_USER }}"
          mode: "{{ item.mode | default('0755') }}"
        with_items:
            - { src: "{{ playbook_dir }}/foot/", dest: "/home/{{ ansible_env.SUDO_USER }}/.config/foot/" }
            - { src: "{{ playbook_dir }}/nvim/", dest: "/home/{{ ansible_env.SUDO_USER }}/.config/nvim/" }
            - { src: "{{ playbook_dir }}/nvim/.vimrc", dest: "/home/{{ ansible_env.SUDO_USER }}/.vimrc" }
            - { src: "{{ playbook_dir }}/bash/.bashrc", dest: "/home/{{ ansible_env.SUDO_USER }}/.bashrc" }
            - { src: "{{ playbook_dir }}/tmux/.tmux.conf", dest: "/home/{{ ansible_env.SUDO_USER }}/.tmux.conf" }

      - name: Install tree-sitter-cli (nvim)
        community.general.npm:
          name: tree-sitter-cli
          global: true
          state: latest

      - name: Git Clone dwl
        git:
          repo: https://github.com/tkyc/dwm.git
          dest: /home/{{ ansible_env.SUDO_USER }}/repo/dwm
          version: dwl
          clone: yes
          update: yes
        become_user: "{{ ansible_env.SUDO_USER }}"

      - name: Build dwl
        shell: |
            cd /home/{{ ansible_env.SUDO_USER }}/repo/dwm
            make clean install
        register: system_build_dwl
      - debug:
          msg: "{{ system_build_dwl }}"

      - name: Enable Audio
        ansible.builtin.systemd:
          name: "{{ item }}"
          enabled: yes
          state: started
          scope: user
        loop:
          - pipewire.service
          - pipewire-pulse.socket
        become: yes
        become_user: "{{ target_user }}"
        environment:
          XDG_RUNTIME_DIR: "/run/user/{{ target_user_uid }}"

