---
- name: Configure arch linux development environment
  hosts: localhost
  connection: local
  become: yes

  tasks:
      - name: Perform System Update
        shell: yes | pacman -Syu
        register: system_update_shell
      - debug:
          msg: "{{ system_update_shell }}"

      - name: Install Required Packages
        pacman:
          name: "{{ item }}"
          state: present
        loop:
          - htop
          - fzf
          - ripgrep
          - tmux
          - openssh
          - firefox
          - cmake
          - unzip
          - zip
          - lsof
          - tree
          - curl
          - less
          - vim
          - nvim
          - wayland
          - wayland-protocols
          - wlroots0.19
          - wl-clipboard
          - wlr-randr
          - foot
          - base-devel
          - grim
          - slurp
          - swaybg
          - swayimg
          - tllist
          - fcft
          - pixman
          - ttf-jetbrains-mono-nerd

      - name: Create Dotfile Directories
        shell: |
            mkdir -p /home/{{ ansible_env.SUDO_USER }}/.config/foot
            mkdir -p /home/{{ ansible_env.SUDO_USER }}/.config/nvim
        register: system_create_dotfile_directories
      - debug:
          msg: "{{ system_create_dotfile_directories }}"

      - name: Copy Dotfiles to Directories
        copy: src={{ item.src }} dest={{ item.dest }}
        with_items:
            - { src: "{{ playbook_dir }}/foot/foot.ini", dest: "/home/{{ ansible_env.SUDO_USER }}/.config/foot/" }
            - { src: "{{ playbook_dir }}/nvim/init.lua", dest: "/home/{{ ansible_env.SUDO_USER }}/.config/nvim/" }
        register: system_copy_dotfiles_to_directories
      - debug:
          msg: "{{ system_copy_dotfiles_to_directories }}"

      - name: Git Clone dwl
        shell: |
            cd /home/{{ ansible_env.SUDO_USER }}/
            cd ~/repo
            git clone -b dwl https://github.com/tkyc/dwm.git
        register: system_git_clone_dwl
      - debug:
          msg: "{{ system_git_clone_dwl }}"

      - name: Build dwl
        shell: |
            cd /home/{{ ansible_env.SUDO_USER }}/
            cd ~/repo/dwl
            sudo make clean install
        register: system_build_dwl
      - debug:
          msg: "{{ system_build_dwl }}"

