---
- name: Configure arch linux development environment
  hosts: localhost
  connection: local
  become: yes

  tasks:
      - name: Perform System Update
        shell: yes | pacman -Syu
        register: system_update_shell
      - debug:
          msg: "{{ system_update_shell }}"

      - name: Install Required Packages
        shell: |
            cd /home/{{ ansible_env.SUDO_USER }}/
            yes | pacman -S htop
            yes | pacman -S fzf
            yes | pacman -S ripgrep
            yes | pacman -S tmux
            yes | pacman -S openssh
            yes | pacman -S firefox
            yes | pacman -S cmake
            yes | pacman -S unzip zip
            yes | pacman -S lsof
            yes | pacman -S tree
            yes | pacman -S curl
            yes | pacman -S less
            yes | pacman -S vim
            yes | pacman -S nvim
            yes | pacman -S wayland
            yes | pacman -S wayland-protocols
            yes | pacman -S wlroots0.19
            yes | pacman -S wl-clipboard
            yes | pacman -S wlr-randr
            yes | pacman -S foot
            yes | pacman -S base-devel
            yes | pacman -S grim
            yes | pacman -S slurp
            yes | pacman -S swaybg
            yes | pacman -S swayimg
            yes | pacman -S tllist
            yes | pacman -S fcft
            yes | pacman -S pixman
            yes | pacman -S ttf-jetbrains-mono-nerd
        register: system_install_required_packages
      - debug:
          msg: "{{ system_install_required_packages }}"

      - name: Create Dotfile Directories
        shell: |
            mkdir -p /home/{{ ansible_env.SUDO_USER }}/.config/foot
            mkdir -p /home/{{ ansible_env.SUDO_USER }}/.config/nvim
        register: system_create_dotfile_directories
      - debug:
          msg: "{{ system_create_dotfile_directories }}"

      - name: Copy Dotfiles to Directories
        copy: src={{ item.src }} dest={{ item.dest }}
        with_items:
            - { src: "{{ playbook_dir }}/foot/foot.ini", dest: "/home/{{ ansible_env.SUDO_USER }}/.config/foot/" }
            - { src: "{{ playbook_dir }}/nvim/init.lua", dest: "/home/{{ ansible_env.SUDO_USER }}/.config/nvim/" }
        register: system_copy_dotfiles_to_directories
      - debug:
          msg: "{{ system_copy_dotfiles_to_directories }}"

      - name: Git Clone dwl
        shell: |
            cd /home/{{ ansible_env.SUDO_USER }}/
            cd ~/repo
            git clone -b dwl https://github.com/tkyc/dwm.git
        register: system_git_clone_dwl
      - debug:
          msg: "{{ system_git_clone_dwl }}"

      - name: Build dwl
        shell: |
            cd /home/{{ ansible_env.SUDO_USER }}/
            cd ~/repo/dwl
            sudo make clean install
        register: system_build_dwl
      - debug:
          msg: "{{ system_build_dwl }}"

