---
- name: Configure arch linux development environment
  hosts: localhost
  connection: local
  become: yes

  tasks:
      - name: Perform System Update
        pacman:
          update_cache: yes
          upgrade: yes

      - name: Install Required Packages
        pacman:
          name: "{{ item }}"
          state: present
        loop:
          - htop
          - fzf
          - ripgrep
          - fd
          - tmux
          - openssh
          - firefox
          - cmake
          - npm
          - unzip
          - zip
          - lsof
          - tree
          - curl
          - less
          - vim
          - nvim
          - wayland
          - wayland-protocols
          - wlroots0.19
          - wl-clipboard
          - wlr-randr
          - foot
          - base-devel
          - grim
          - slurp
          - swaybg
          - swayimg
          - tllist
          - fcft
          - pixman
          - ttf-jetbrains-mono-nerd
          - pipewire
          - pipewire-pulse
          - pipewire-alsa
          - wireplumber

      - name: Create Config Directory
        shell: |
            mkdir -p /home/{{ ansible_env.SUDO_USER }}/.config

      - name: Copy Files to Directories
        copy: src={{ item.src }} dest={{ item.dest }}
        with_items:
            - { src: "{{ playbook_dir }}/foot/", dest: "/home/{{ ansible_env.SUDO_USER }}/.config/foot/" }
            - { src: "{{ playbook_dir }}/nvim/", dest: "/home/{{ ansible_env.SUDO_USER }}/.config/nvim/" }

      - name: Git Clone dwl
        git:
          repo: https://github.com/tkyc/dwm.git
          dest: /home/{{ ansible_env.SUDO_USER }}/repo/dwm
          version: dwl
          clone: yes
          update: yes

      - name: Build dwl
        shell: |
            cd /home/{{ ansible_env.SUDO_USER }}/repo/dwm
            make clean install
        register: system_build_dwl
      - debug:
          msg: "{{ system_build_dwl }}"

      - name: Enable Audio
        shell: |
            systemctl --user enable pipewire.service pipewire-pulse.socket
            systemctl --user start pipewire.service pipewire-pulse.socket
        register: system_enable_audio
      - debug:
          msg: "{{ system_enable_audio }}"

